using System;
using System.Net;
using System.Net.Sockets;
using System.Text;
using Encryption;

namespace Server
{
    class Program
    {
        static void Main(string[] args)
        {
            // Setup.
            IPAddress IP = IPAddress.Any;
            int Port = 11000;
            IPEndPoint RemoteHost = new IPEndPoint(IP, Port);
            //

            using (UdpClient udpServer = new UdpClient(Port))
            {
                SecurityController _security = new SecurityController();
                // Password for decrypting AES protected strings the client is sending you.
                string AESPassword = "Password123";

                while (true)
                {
                    try
                    {
                        // Receive the packet, translate and send back.
                        byte[] ReceivePacket = udpServer.Receive(ref RemoteHost);
                        string TranslatePacket = _security.Decrypt(AESPassword, PacketXOR(Encoding.UTF8.GetString(ReceivePacket)));

                        byte[] SendPacket = Encoding.ASCII.GetBytes(PacketXOR(TranslatePacket));
                        udpServer.Send(SendPacket, SendPacket.Length, RemoteHost);

                        // Logging.
                        Console.WriteLine($"IP: {RemoteHost.ToString()}");
                        Console.WriteLine($"Encrypted String: {PacketXOR(Encoding.UTF8.GetString(ReceivePacket))}");
                        Console.ForegroundColor = ConsoleColor.Green;
                        Console.WriteLine($"Decrypted String: {TranslatePacket} has been sent back to the remote host." + "\n");
                        Console.ResetColor();
                    }
                    catch (Exception ex)
                    {
                        // Sending the exception back to the remote host.
                        byte[] SendExPacket = Encoding.ASCII.GetBytes(PacketXOR($"Error: {ex.Message.ToString()}"));
                        udpServer.Send(SendExPacket, SendExPacket.Length, RemoteHost);

                        // Logging.
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("\n" + "Error: {0}", ex + "\n");
                        Console.ResetColor();
                    }
                }
            }
        }

        // Masking the plain-text (mind your own business, WireShark) in the packets with a simple XOR.
        private static string PacketXOR(string input)
        {
            char[] ProcessKey =
             {
                Convert.ToChar(86),
                Convert.ToChar(87),
                Convert.ToChar(53),
                Convert.ToChar(79),
                Convert.ToChar(78),
                Convert.ToChar(85),
                Convert.ToChar(120),
                Convert.ToChar(117),
                Convert.ToChar(78),
                Convert.ToChar(110),
                Convert.ToChar(111),
                Convert.ToChar(122),
                Convert.ToChar(90),
                Convert.ToChar(84),
                Convert.ToChar(90),
                Convert.ToChar(104),
                Convert.ToChar(99),
                Convert.ToChar(106),
                Convert.ToChar(85),
                Convert.ToChar(52),
                Convert.ToChar(86),
                Convert.ToChar(68),
                Convert.ToChar(99),
                Convert.ToChar(52),
                Convert.ToChar(78),
                Convert.ToChar(71),
                Convert.ToChar(73),
                Convert.ToChar(51),
                Convert.ToChar(78),
                Convert.ToChar(68),
                Convert.ToChar(74),
                Convert.ToChar(66),
                Convert.ToChar(82),
                Convert.ToChar(106),
                Convert.ToChar(86),
                Convert.ToChar(112),
                Convert.ToChar(77),
                Convert.ToChar(106),
                Convert.ToChar(107),
                Convert.ToChar(119),
                Convert.ToChar(83),
                Convert.ToChar(107),
                Convert.ToChar(56),
                Convert.ToChar(51),
                Convert.ToChar(98),
                Convert.ToChar(72),
                Convert.ToChar(108),
                Convert.ToChar(74),
                Convert.ToChar(78),
                Convert.ToChar(68),
                Convert.ToChar(69),
                Convert.ToChar(52),
                Convert.ToChar(85),
                Convert.ToChar(51),
                Convert.ToChar(107),
                Convert.ToChar(122),
                Convert.ToChar(98),
                Convert.ToChar(85),
                Convert.ToChar(86),
                Convert.ToChar(108),
                Convert.ToChar(85),
                Convert.ToChar(110),
                Convert.ToChar(81),
                Convert.ToChar(49),
                Convert.ToChar(89),
                Convert.ToChar(84),
                Convert.ToChar(90),
                Convert.ToChar(48),
                Convert.ToChar(77),
                Convert.ToChar(122),
                Convert.ToChar(69),
                Convert.ToChar(119),
                Convert.ToChar(78),
                Convert.ToChar(69),
                Convert.ToChar(86),
                Convert.ToChar(117),
                Convert.ToChar(89),
                Convert.ToChar(86),
                Convert.ToChar(70),
                Convert.ToChar(87),
                Convert.ToChar(78),
                Convert.ToChar(106),
                Convert.ToChar(73),
                Convert.ToChar(53),
                Convert.ToChar(84),
                Convert.ToChar(110),
                Convert.ToChar(78),
                Convert.ToChar(54),
                Convert.ToChar(85),
                Convert.ToChar(85),
                Convert.ToChar(82),
                Convert.ToChar(109),
                Convert.ToChar(78),
                Convert.ToChar(68),
                Convert.ToChar(104),
                Convert.ToChar(81),
                Convert.ToChar(85),
                Convert.ToChar(85),
                Convert.ToChar(53),
                Convert.ToChar(116),
                Convert.ToChar(83),
                Convert.ToChar(106),
                Convert.ToChar(77),
                Convert.ToChar(53),
                Convert.ToChar(87),
                Convert.ToChar(106),
                Convert.ToChar(104),
                Convert.ToChar(112),
                Convert.ToChar(87),
                Convert.ToChar(106),
                Convert.ToChar(73),
                Convert.ToChar(49),
                Convert.ToChar(77),
                Convert.ToChar(50),
                Convert.ToChar(120),
                Convert.ToChar(54),
                Convert.ToChar(85),
                Convert.ToChar(106),
                Convert.ToChar(99),
                Convert.ToChar(122),
                Convert.ToChar(83),
                Convert.ToChar(86),
                Convert.ToChar(108),
                Convert.ToChar(110),
                Convert.ToChar(77),
                Convert.ToChar(106),
                Convert.ToChar(100),
                Convert.ToChar(104),
                Convert.ToChar(89),
                Convert.ToChar(122),
                Convert.ToChar(89),
                Convert.ToChar(120),
                Convert.ToChar(79),
                Convert.ToChar(68),
                Convert.ToChar(108),
                Convert.ToChar(52),
                Convert.ToChar(79),
                Convert.ToChar(86),
                Convert.ToChar(100),
                Convert.ToChar(73),
                Convert.ToChar(78),
                Convert.ToChar(84),
                Convert.ToChar(104),
                Convert.ToChar(105),
                Convert.ToChar(100),
                Convert.ToChar(48),
                Convert.ToChar(103),
                Convert.ToChar(52),
                Convert.ToChar(77),
                Convert.ToChar(68),
                Convert.ToChar(77),
                Convert.ToChar(51),
                Convert.ToChar(77),
                Convert.ToChar(106),
                Convert.ToChar(85),
                Convert.ToChar(49),
                Convert.ToChar(78),
                Convert.ToChar(87),
                Convert.ToChar(74),
                Convert.ToChar(54),
                Convert.ToChar(78),
                Convert.ToChar(68),
                Convert.ToChar(89),
                Convert.ToChar(50),
                Convert.ToChar(77),
                Convert.ToChar(87),
                Convert.ToChar(100),
                Convert.ToChar(79),
                Convert.ToChar(98),
                Convert.ToChar(84),
                Convert.ToChar(99),
                Convert.ToChar(51),
                Convert.ToChar(78),
                Convert.ToChar(49),
                Convert.ToChar(78),
                Convert.ToChar(115),
                Convert.ToChar(78),
                Convert.ToChar(72),
                Convert.ToChar(103),
                Convert.ToChar(51),
                Convert.ToChar(83),
                Convert.ToChar(109),
                Convert.ToChar(120),
                Convert.ToChar(79),
                Convert.ToChar(77),
                Convert.ToChar(84),
                Convert.ToChar(74),
                Convert.ToChar(121),
                Convert.ToChar(78),
                Convert.ToChar(87),
                Convert.ToChar(107),
                Convert.ToChar(51),
                Convert.ToChar(101),
                Convert.ToChar(106),
                Convert.ToChar(74),
                Convert.ToChar(116),
                Convert.ToChar(81),
                Convert.ToChar(49),
                Convert.ToChar(73),
                Convert.ToChar(120),
                Convert.ToChar(100),
                Convert.ToChar(84),
                Convert.ToChar(66),
                Convert.ToChar(54),
                Convert.ToChar(77),
                Convert.ToChar(84),
                Convert.ToChar(70),
                Convert.ToChar(85),
                Convert.ToChar(78),
                Convert.ToChar(84),
                Convert.ToChar(90),
                Convert.ToChar(111),
                Convert.ToChar(77),
                Convert.ToChar(86),
                Convert.ToChar(70),
                Convert.ToChar(76),
                Convert.ToChar(79),
                Convert.ToChar(87),
                Convert.ToChar(85),
                Convert.ToChar(50),
                Convert.ToChar(78),
                Convert.ToChar(106),
                Convert.ToChar(86),
                Convert.ToChar(90),
                Convert.ToChar(83),
                Convert.ToChar(70),
                Convert.ToChar(74),
                Convert.ToChar(54),
                Convert.ToChar(90),
                Convert.ToChar(110),
                Convert.ToChar(66),
                Convert.ToChar(54),
                Convert.ToChar(99),
                Convert.ToChar(84),
                Convert.ToChar(103),
                Convert.ToChar(52),
                Convert.ToChar(83),
                Convert.ToChar(87),
                Convert.ToChar(70),
                Convert.ToChar(79),
                Convert.ToChar(86),
                Convert.ToChar(107),
                Convert.ToChar(77),
                Convert.ToChar(119),
                Convert.ToChar(79),
                Convert.ToChar(86),
                Convert.ToChar(74),
                Convert.ToChar(74),
                Convert.ToChar(101),
                Convert.ToChar(110),
                Convert.ToChar(99),
                Convert.ToChar(119),
                Convert.ToChar(77),
                Convert.ToChar(84),
                Convert.ToChar(104),
                Convert.ToChar(71),
                Convert.ToChar(86),
                Convert.ToChar(108),
                Convert.ToChar(78),
                Convert.ToChar(68),
                Convert.ToChar(86),
                Convert.ToChar(50),
                Convert.ToChar(74),
                Convert.ToChar(118),
                Convert.ToChar(77),
                Convert.ToChar(106),
                Convert.ToChar(65),
                Convert.ToChar(119),
                Convert.ToChar(86),
                Convert.ToChar(106),
                Convert.ToChar(99),
                Convert.ToChar(48),
                Convert.ToChar(77),
                Convert.ToChar(71),
                Convert.ToChar(70),
                Convert.ToChar(71),
                Convert.ToChar(90),
                Convert.ToChar(70),
                Convert.ToChar(78),
                Convert.ToChar(106),
                Convert.ToChar(82),
                Convert.ToChar(122),
                Convert.ToChar(86),
                Convert.ToChar(89),
                Convert.ToChar(77),
                Convert.ToChar(122),
                Convert.ToChar(100),
                Convert.ToChar(71),
                Convert.ToChar(77),
                Convert.ToChar(85),
                Convert.ToChar(90),
                Convert.ToChar(68),
                Convert.ToChar(77),
                Convert.ToChar(48),
                Convert.ToChar(119),
                Convert.ToChar(52),
                Convert.ToChar(84),
                Convert.ToChar(68),
                Convert.ToChar(82),
                Convert.ToChar(84),
                Convert.ToChar(77),
                Convert.ToChar(68),
                Convert.ToChar(89),
                Convert.ToChar(122),
                Convert.ToChar(100),
                Convert.ToChar(85),
                Convert.ToChar(104),
                Convert.ToChar(105),
                Convert.ToChar(77),
                Convert.ToChar(68),
                Convert.ToChar(85),
                Convert.ToChar(120),
                Convert.ToChar(86),
                Convert.ToChar(107),
                Convert.ToChar(86),
                Convert.ToChar(83),
                Convert.ToChar(77),
                Convert.ToChar(107),
                Convert.ToChar(100),
                Convert.ToChar(97),
                Convert.ToChar(89),
                Convert.ToChar(84),
                Convert.ToChar(74),
                Convert.ToChar(54),
                Convert.ToChar(77),
                Convert.ToChar(84),
                Convert.ToChar(81),
                Convert.ToChar(122),
                Convert.ToChar(99),
                Convert.ToChar(110),
                Convert.ToChar(90),
                Convert.ToChar(79),
                Convert.ToChar(77),
                Convert.ToChar(48),
                Convert.ToChar(73),
                Convert.ToChar(48),
                Convert.ToChar(82),
                Convert.ToChar(88),
                Convert.ToChar(89),
                Convert.ToChar(61)
            };

            byte[] FinalKey = Convert.FromBase64CharArray(ProcessKey, 0, ProcessKey.Length);
            char[] output = new char[input.Length];

            for (int i = 0; i < input.Length; i++)
            {
                output[i] = (char)(input[i] ^ FinalKey[i % FinalKey.Length]);
            }

            Array.Clear(ProcessKey, 0, ProcessKey.Length);
            Array.Clear(FinalKey, 0, FinalKey.Length);

            return new string(output);
        }
    }
}